---
upload_path: "/img/uploads/:year:/:month:"
frontmatter_file_url_template: "/img/uploads/:year:/:month:"
body_file_url_template: "/img/uploads/:year:/:month:"
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
collections: 
